### ISSUE TITLE
doesn't work anymore with ios9

### ISSUE THREAD

**Issue by ck-on** [lazd/iNoBounce#17]
Your demo only works if there is no momentum with existing scrolling.

Once there is scroll in motion, if you keep trying to scroll, the screen will bounce.

**Comment by lazd** [comment]
@ck-on I just tested it on iOS 9.0.3 on a iPhone 5S, and it works as designed.

The **viewport** should not rubberband, but the **scroll area** itself should rubberband.

That is, you should not be able to get this to happen (viewport rubberbanding): 

![screen shot 2015-10-08 at 10 06 08 am](https://cloud.githubusercontent.com/assets/201344/10373756/38b817cc-6da4-11e5-9e3a-3dced814bdb5.png)

But you should be able to get this to happen (local rubberbanding):

![screen shot 2015-10-08 at 10 05 54 am](https://cloud.githubusercontent.com/assets/201344/10373757/38bd1a4c-6da4-11e5-9e7a-31fe0b1dfd46.png)

However, due to #7, you won't be able to get local rubberbanding to happen without momentum.
