### ISSUE TITLE
ios10 don't work

### ISSUE THREAD

**Issue by gg343917542** [lazd/iNoBounce#35]
how to  resolve?

**Comment by lazd** [comment]
Can you be any more specific?

**Comment by gg343917542** [comment]
@lazd This is my problem.Now it's ok

**Comment by lazd** [comment]
????

**Comment by lazd** [comment]
I'm going to go ahead and assume you solved your problem. In the future, know that filing an issue that simply says `it don't work` is rude, lazy, and downright abusive to members of the open source community that maintain the software you use. Learn how to contribute detailed issue reports and don't waste people's precious, donated time by making them extract information out of you to help you solve you problem, and please, if you figured out the issue *post what you did to fix it* instead of selfishly saying `it works now` and moving on as if nobody will ever have the same problem and you don't care to leave them a helpful hint if they do.

/rant
